server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.60.12/lab_sys_v2 #?servierTimezone=UTC
    username: root
    password: digcow.com
  main:
    banner-mode: off
  session:
    store-type: none
  mvc:
    view:
      prefix: /webapp
      suffix: .html


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false



